apiVersion: apps/v1
kind: Deployment
metadata:
  name: bolt-diy
spec:
  replicas: 200  # Scale to 200 instances
  selector:
    matchLabels:
      app: bolt-diy
  template:
    metadata:
      labels:
        app: bolt-diy
    spec:
      containers:
      - name: bolt-diy
        image: bolt-ai:production
        ports:
        - containerPort: 5173
        env:
        - name: GITHUB_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: bolt-secrets
              key: github-token
        # Add other environment variables as needed
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 5173
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5173
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: bolt-diy-service
spec:
  selector:
    app: bolt-diy
  ports:
  - port: 80
    targetPort: 5173
  type: LoadBalancer
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bolt-diy-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bolt-diy
  minReplicas: 50
  maxReplicas: 250
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70