apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bolt-diy.fullname" . }}-secrets
  labels:
    {{- include "bolt-diy.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secretEnv }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}